server:
  port: 2525

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/118-g6?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12qwaszxQq
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#http配置服务
http:
  #最大连接数
  maxTotal : 100
  #并发数
  defaultMaxPerRoute : 20
  #创建连接的最长时间
  connectTimeout : 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout : 500
  #数据传输的最长时间
  socketTimeout : 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled : true